"""Post-GA: the shareable, participant-facing Recap.

Competitive-analysis follow-up (Abridge/Nabla/Heidi all generate an
after-visit-style summary meant for the OTHER party in the conversation,
e.g. a patient after-visit summary or a meeting recap for an external
attendee). VocaDox's existing `Document`/`DocumentRevision`
(app.documents) is the internal, evidence-traceable record and is
deliberately never composed by an LLM (see that module's docstring). A
Recap is a distinct, separate artifact:

- generated by a real LLM call (via app.providers.llm.LLMProvider),
  always explicitly labeled as AI-generated
- built from the conversation's already-composed Document content, never
  raw transcript directly, and instructed to add nothing beyond it
- must be explicitly approved by a human (`recap:approve`) before it is
  considered ready to share — the AI never self-approves, matching every
  other AI-produced artifact in this project

See alembic/versions/0014_recaps.py for the schema rationale.
"""
