import { useMutation, useQuery, useQueryClient, type UseQueryResult } from "@tanstack/react-query";
import {
  CheckCircle2,
  FileQuestion,
  FileText,
  ListChecks,
  ListTree,
  MessageCircle,
  MessagesSquare,
  MoreHorizontal,
  RefreshCw,
  Sparkles,
  StickyNote,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";

import {
  type ProtocolItem,
  type ProtocolSection,
  type ProtocolSectionType,
  type ProtocolSource,
  generateProtocol,
  getItemSources,
  getProtocol,
  getSectionSources,
} from "../api/protocols";
import { ApiError } from "../api/client";
import { getProcessingStatus, type ProcessingJob } from "../api/transcription";
import { useAuth } from "../auth/useAuth";
import { Badge } from "../design-system/Badge";
import { Button } from "../design-system/Button";
import { Card } from "../design-system/Card";
import { EmptyState, ErrorState, Skeleton } from "../design-system/States";
import type { AudioPlayerHandle } from "./AudioPlayer";
import styles from "./ProtocolPanel.module.css";

const SECTION_ICONS: Record<ProtocolSectionType, typeof FileText> = {
  introduction: MessageCircle,
  topic: MessagesSquare,
  facts: FileText,
  discussion: MessagesSquare,
  decision: CheckCircle2,
  action_items: ListChecks,
  open_questions: FileQuestion,
  note: StickyNote,
  conclusion: CheckCircle2,
};

function formatMs(ms: number): string {
  const totalSeconds = Math.round(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}

interface ProtocolPanelProps {
  conversationId: string;
  audioPlayerRef: React.RefObject<AudioPlayerHandle | null>;
  onOpenTranscript: (segmentId: string) => void;
}

/**
 * Post-GA "Protokoll" tab: a structured, chronological representation of
 * the conversation (sections/items, generated by one LLM call — see
 * app.protocols.service.run_protocol_generation), distinct from both
 * Transkript (verbatim) and Dokumentation (a formal generated document —
 * deterministic composition, never touched by this panel). See
 * docs/architecture/adr/0042-protokoll.md.
 *
 * Follows FactsPanel.tsx's self-fetching structure exactly
 * (conversationId + audioPlayerRef props, own useQuery calls).
 */
export function ProtocolPanel({ conversationId, audioPlayerRef, onOpenTranscript }: ProtocolPanelProps) {
  const { csrfToken, hasPermission } = useAuth();
  const queryClient = useQueryClient();
  const [error, setError] = useState<string | null>(null);
  // Tracks the id of the last generate_protocol job whose completion we
  // already reacted to, so the effect below fires exactly once per job
  // instead of on every poll tick.
  const lastHandledJobRef = useRef<string | null>(null);

  const protocolQuery = useQuery({
    queryKey: ["protocol", conversationId],
    queryFn: () => getProtocol(conversationId),
  });

  // Always mounted (mirrors TranscriptPanel's processingQuery), self-
  // pacing via refetchInterval rather than a local "am I generating"
  // boolean — a GENERATING protocol has no DB row of its own (see
  // app.protocols.service's module docstring), so "is generation running"
  // is answered by the job list, not by GET .../protocol.
  const processingQuery = useQuery({
    queryKey: ["processing-status", conversationId],
    queryFn: () => getProcessingStatus(conversationId),
    refetchInterval: (query) => {
      const jobs = query.state.data?.jobs ?? [];
      const active = jobs.some(
        (j) => j.job_type === "generate_protocol" && (j.status === "queued" || j.status === "running")
      );
      return active ? 1500 : false;
    },
  });

  // `jobs` is ordered by queued_at DESC (see transcriptStage.ts), so the
  // first generate_protocol entry is always the most recent attempt.
  const latestJob = processingQuery.data?.jobs.find((j) => j.job_type === "generate_protocol");
  const isGenerating = latestJob?.status === "queued" || latestJob?.status === "running";

  // Edge-triggered on the job finishing (success or failure) — refresh
  // the protocol data, or surface the failure. Without this, the panel
  // would only ever pick up a newly generated revision on the next full
  // page load, since GET .../protocol itself is never polled.
  useEffect(() => {
    if (!latestJob) return;
    if (latestJob.status !== "succeeded" && latestJob.status !== "failed") return;
    if (lastHandledJobRef.current === latestJob.id) return;
    lastHandledJobRef.current = latestJob.id;
    if (latestJob.status === "succeeded") {
      void queryClient.invalidateQueries({ queryKey: ["protocol", conversationId] });
    } else {
      setError("Protokoll konnte nicht erstellt werden.");
    }
  }, [latestJob, conversationId, queryClient]);

  const generateMutation = useMutation({
    mutationFn: () => generateProtocol(conversationId, csrfToken ?? ""),
    onError: (err) => setError(err instanceof ApiError ? err.message : "Protokoll konnte nicht erstellt werden."),
    onSuccess: () => {
      setError(null);
      void queryClient.invalidateQueries({ queryKey: ["processing-status", conversationId] });
    },
  });

  if (protocolQuery.isLoading) return <Skeleton height="10rem" />;

  if (generateMutation.isPending || isGenerating) {
    return <GeneratingState job={latestJob} />;
  }

  const revision = protocolQuery.data?.current_revision;

  if (!revision) {
    return (
      <Card>
        <EmptyState
          icon={<Sparkles size={18} aria-hidden="true" />}
          title="Noch kein Protokoll erstellt"
          description="VocaDox kann das Gespräch automatisch in Themen, Entscheidungen und nächste Schritte strukturieren. Das Originaltranskript bleibt unverändert."
          action={
            hasPermission("protocol:generate") ? (
              <Button variant="primary" type="button" onClick={() => generateMutation.mutate()}>
                Protokoll erstellen
              </Button>
            ) : undefined
          }
        />
        {error && <ErrorState message={error} />}
      </Card>
    );
  }

  return (
    <div>
      <div className={styles.header}>
        <div className={styles.headerText}>
          <h2 style={{ fontSize: "var(--font-h2-size)" }}>Protokoll</h2>
          <p>
            Das Gespräch wurde automatisch in {revision.sections.length}{" "}
            {revision.sections.length === 1 ? "Abschnitt" : "Abschnitte"} strukturiert.
          </p>
        </div>
        <div className={styles.headerActions}>
          <Badge tone="success">Aktuell</Badge>
          {hasPermission("protocol:generate") && (
            <Button variant="secondary" type="button" onClick={() => generateMutation.mutate()}>
              <RefreshCw size={14} aria-hidden="true" /> Neu erstellen
            </Button>
          )}
        </div>
      </div>

      {error && <ErrorState message={error} onRetry={() => generateMutation.mutate()} />}

      <div className={styles.timeline}>
        {revision.sections.map((section, index) => (
          <div className={styles.row} key={section.id}>
            <div className={styles.timeCol}>
              {section.start_ms !== null ? formatMs(section.start_ms) : ""}
            </div>
            <div className={styles.nodeCol}>
              <div className={styles.node} />
              {index < revision.sections.length - 1 && <div className={styles.nodeLine} />}
            </div>
            <div className={styles.cardCol}>
              <SectionCard
                conversationId={conversationId}
                section={section}
                audioPlayerRef={audioPlayerRef}
                onOpenTranscript={onOpenTranscript}
              />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function GeneratingState({ job }: { job: ProcessingJob | undefined }) {
  const steps = [
    { label: "Transkript analysiert", done: true },
    { label: "Themen erkannt", done: job?.status === "running" },
    { label: "Entscheidungen und Aufgaben extrahieren", done: false },
    { label: "Protokoll speichern", done: false },
  ];
  return (
    <Card>
      <p style={{ fontWeight: 600 }}>Protokoll wird erstellt …</p>
      <ul className={styles.progressList}>
        {steps.map((step) => (
          <li
            key={step.label}
            className={`${styles.progressItem} ${step.done ? styles.progressItemDone : ""}`}
          >
            {step.done ? (
              <CheckCircle2 size={14} aria-hidden="true" />
            ) : (
              <span aria-hidden="true">○</span>
            )}
            {step.label}
          </li>
        ))}
      </ul>
    </Card>
  );
}

function SectionCard({
  conversationId,
  section,
  audioPlayerRef,
  onOpenTranscript,
}: {
  conversationId: string;
  section: ProtocolSection;
  audioPlayerRef: React.RefObject<AudioPlayerHandle | null>;
  onOpenTranscript: (segmentId: string) => void;
}) {
  const Icon = SECTION_ICONS[section.section_type] ?? ListTree;
  const importantPoints = section.items.filter((i) => i.item_type === "important_point");
  const decisions = section.items.filter((i) => i.item_type === "decision");
  const openQuestions = section.items.filter((i) => i.item_type === "open_question");
  const actionItems = section.items.filter((i) => i.item_type === "action_item");
  const otherItems = section.items.filter(
    (i) => !["important_point", "decision", "open_question", "action_item"].includes(i.item_type)
  );

  return (
    <Card>
      <div id={`protocol-section-${section.id}`} style={{ scrollMarginTop: "80px" }}>
        <div className={styles.sectionHeader}>
          <Icon size={16} aria-hidden="true" />
          <span className={styles.sectionTitle}>{section.title}</span>
        </div>
        <p className={styles.sectionSummary}>{section.summary}</p>

        {importantPoints.length > 0 && (
          <div className={`${styles.block} ${styles.blockImportant}`}>
            <div className={styles.blockLabel}>Wichtige Punkte</div>
            <ul className={styles.itemList}>
              {importantPoints.map((item) => (
                <ItemWithSources
                  key={item.id}
                  conversationId={conversationId}
                  item={item}
                  audioPlayerRef={audioPlayerRef}
                  onOpenTranscript={onOpenTranscript}
                >
                  • {item.text}
                </ItemWithSources>
              ))}
            </ul>
          </div>
        )}

        {decisions.length > 0 && (
          <div className={`${styles.block} ${styles.blockDecision}`}>
            <div className={styles.blockLabel}>Beschlüsse</div>
            <ul className={styles.itemList}>
              {decisions.map((item) => (
                <ItemWithSources
                  key={item.id}
                  conversationId={conversationId}
                  item={item}
                  audioPlayerRef={audioPlayerRef}
                  onOpenTranscript={onOpenTranscript}
                >
                  ✓ {item.text}
                </ItemWithSources>
              ))}
            </ul>
          </div>
        )}

        {openQuestions.length > 0 && (
          <div className={`${styles.block} ${styles.blockOpenQuestion}`}>
            <div className={styles.blockLabel}>Offene Punkte</div>
            <ul className={styles.itemList}>
              {openQuestions.map((item) => (
                <ItemWithSources
                  key={item.id}
                  conversationId={conversationId}
                  item={item}
                  audioPlayerRef={audioPlayerRef}
                  onOpenTranscript={onOpenTranscript}
                >
                  ! {item.text}
                </ItemWithSources>
              ))}
            </ul>
          </div>
        )}

        {actionItems.length > 0 && (
          <div className={`${styles.block} ${styles.blockAction}`}>
            <div className={styles.blockLabel}>Nächste Schritte</div>
            <ul className={styles.itemList}>
              {actionItems.map((item) => (
                <ItemWithSources
                  key={item.id}
                  conversationId={conversationId}
                  item={item}
                  audioPlayerRef={audioPlayerRef}
                  onOpenTranscript={onOpenTranscript}
                >
                  <span className={styles.actionItem}>
                    <input type="checkbox" checked={Boolean(item.completed)} disabled />
                    <span>
                      {item.text}
                      {(item.responsible_label || item.due_date) && (
                        <span className={styles.actionItemMeta}>
                          {" "}
                          — {[item.responsible_label, item.due_date].filter(Boolean).join(" · ")}
                        </span>
                      )}
                    </span>
                  </span>
                </ItemWithSources>
              ))}
            </ul>
          </div>
        )}

        {otherItems.length > 0 && (
          <div className={styles.block}>
            <ul className={styles.itemList}>
              {otherItems.map((item) => (
                <ItemWithSources
                  key={item.id}
                  conversationId={conversationId}
                  item={item}
                  audioPlayerRef={audioPlayerRef}
                  onOpenTranscript={onOpenTranscript}
                >
                  {item.text}
                </ItemWithSources>
              ))}
            </ul>
          </div>
        )}

        <div className={styles.sectionFooter}>
          <SourcesDisclosure
            conversationId={conversationId}
            kind="section"
            id={section.id}
            audioPlayerRef={audioPlayerRef}
            onOpenTranscript={onOpenTranscript}
          />
        </div>
      </div>
    </Card>
  );
}

/** Shared rendering for a resolved-sources list — used both by the
 * section-level disclosure and the per-item one below. An empty list is
 * rendered honestly ("Keine verknüpfte Quelle"), never hidden — a
 * section or item can legitimately have no resolvable citation (see
 * app.protocols.service._resolve_sources: a claimed-but-nonexistent
 * segment sequence is silently dropped, never fabricated). */
function SourceQuoteList({
  sourcesQuery,
  audioPlayerRef,
  onOpenTranscript,
}: {
  sourcesQuery: UseQueryResult<ProtocolSource[]>;
  audioPlayerRef: React.RefObject<AudioPlayerHandle | null>;
  onOpenTranscript: (segmentId: string) => void;
}) {
  return (
    <div className={styles.sourceList}>
      {sourcesQuery.isLoading && <Skeleton height="1.5rem" />}
      {sourcesQuery.data && sourcesQuery.data.length === 0 && (
        <p style={{ color: "var(--text-muted)" }}>Keine verknüpfte Quelle.</p>
      )}
      {sourcesQuery.data?.map((source) => (
        <div key={source.id} className={styles.sourceItem}>
          <button
            type="button"
            className={styles.sourceQuote}
            onClick={() => audioPlayerRef.current?.seekToMs(source.segment_start_ms)}
          >
            {formatMs(source.segment_start_ms)}{" "}
            {source.speaker_label && <span className={styles.sourceSpeaker}>{source.speaker_label}</span>}
            <br />
            &ldquo;{source.segment_text}&rdquo;
          </button>
          <Button variant="tertiary" type="button" onClick={() => onOpenTranscript(source.transcript_segment_id)}>
            Im Transkript öffnen
          </Button>
        </div>
      ))}
    </div>
  );
}

function SourcesDisclosure({
  conversationId,
  kind,
  id,
  audioPlayerRef,
  onOpenTranscript,
}: {
  conversationId: string;
  kind: "section" | "item";
  id: string;
  audioPlayerRef: React.RefObject<AudioPlayerHandle | null>;
  onOpenTranscript: (segmentId: string) => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const sourcesQuery = useQuery({
    queryKey: ["protocol-sources", kind, id],
    queryFn: () =>
      kind === "section" ? getSectionSources(conversationId, id) : getItemSources(conversationId, id),
    enabled: expanded,
  });

  return (
    <div>
      <Button variant="tertiary" type="button" onClick={() => setExpanded((e) => !e)}>
        <MoreHorizontal size={14} aria-hidden="true" /> Quelle anzeigen
      </Button>
      {expanded && (
        <SourceQuoteList sourcesQuery={sourcesQuery} audioPlayerRef={audioPlayerRef} onOpenTranscript={onOpenTranscript} />
      )}
    </div>
  );
}

/** Per-item traceability: each bullet gets its own small source toggle
 * (most real citations resolve at the item level, not the section level
 * — a section's own "Quelle anzeigen" is often honestly empty even when
 * every one of its items has real sources). */
function ItemWithSources({
  conversationId,
  item,
  audioPlayerRef,
  onOpenTranscript,
  children,
}: {
  conversationId: string;
  item: ProtocolItem;
  audioPlayerRef: React.RefObject<AudioPlayerHandle | null>;
  onOpenTranscript: (segmentId: string) => void;
  children: React.ReactNode;
}) {
  const [expanded, setExpanded] = useState(false);
  const sourcesQuery = useQuery({
    queryKey: ["protocol-sources", "item", item.id],
    queryFn: () => getItemSources(conversationId, item.id),
    enabled: expanded,
  });

  return (
    <li>
      <div className={styles.itemRowMain}>
        <span>{children}</span>
        <button
          type="button"
          className={styles.itemSourceToggle}
          onClick={() => setExpanded((e) => !e)}
          aria-expanded={expanded}
          title="Quelle anzeigen"
        >
          <MoreHorizontal size={12} aria-hidden="true" />
        </button>
      </div>
      {expanded && (
        <SourceQuoteList sourcesQuery={sourcesQuery} audioPlayerRef={audioPlayerRef} onOpenTranscript={onOpenTranscript} />
      )}
    </li>
  );
}
